ALTER SESSION SET CONTAINER=ORCLPDB1;

CREATE OR REPLACE DIRECTORY MY_IMPORT_DIR AS '/opt/oracle/import';

CREATE USER liferay IDENTIFIED BY liferay123;
GRANT CONNECT, RESOURCE, DBA TO liferay;
GRANT UNLIMITED TABLESPACE TO liferay;

GRANT READ, WRITE ON DIRECTORY MY_IMPORT_DIR TO LIFERAY;

CREATE TABLESPACE LIFEPROD_DATA DATAFILE '/opt/oracle/oradata/LIFEPROD_DATA01.dbf' SIZE 1G AUTOEXTEND on next 10m maxsize unlimited;

CREATE PROFILE SERVICE_ACCOUNT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;

CREATE USER "LPORTAL_CUSCAL_6.2" IDENTIFIED BY liferay123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE SERVICE_ACCOUNT;
GRANT CONNECT, RESOURCE, DBA TO "LPORTAL_CUSCAL_6.2";

CREATE USER LPORTAL_CUSCAL_73 IDENTIFIED BY liferay123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE SERVICE_ACCOUNT;
GRANT CONNECT, RESOURCE, DBA TO LPORTAL_CUSCAL_73;

CREATE USER LPORTAL_CUSCAL_UAT IDENTIFIED BY liferay123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE SERVICE_ACCOUNT;
GRANT CONNECT, RESOURCE, DBA TO LPORTAL_CUSCAL_UAT;