/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package au.com.cuscal.termsofuse.model.impl;

import au.com.cuscal.termsofuse.model.TermsOfUse;
import au.com.cuscal.termsofuse.service.TermsOfUseLocalServiceUtil;

/**
 * The extended model base implementation for the TermsOfUse service. Represents a row in the &quot;CuscalToC_TermsOfUse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TermsOfUseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TermsOfUseImpl
 * @see TermsOfUse
 * @generated
 */
public abstract class TermsOfUseBaseImpl
	extends TermsOfUseModelImpl implements TermsOfUse {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a terms of use model instance should use the <code>TermsOfUse</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TermsOfUseLocalServiceUtil.addTermsOfUse(this);
		}
		else {
			TermsOfUseLocalServiceUtil.updateTermsOfUse(this);
		}
	}

}