/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package au.com.cuscal.termsofuse.model.impl;

import au.com.cuscal.termsofuse.model.TermsOfUse;
import au.com.cuscal.termsofuse.model.TermsOfUseModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TermsOfUse service. Represents a row in the &quot;CuscalToC_TermsOfUse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TermsOfUseModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TermsOfUseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TermsOfUseImpl
 * @generated
 */
@JSON(strict = true)
public class TermsOfUseModelImpl
	extends BaseModelImpl<TermsOfUse> implements TermsOfUseModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a terms of use model instance should use the <code>TermsOfUse</code> interface instead.
	 */
	public static final String TABLE_NAME = "CuscalToC_TermsOfUse";

	public static final Object[][] TABLE_COLUMNS = {
		{"entryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"screenName", Types.VARCHAR}, {"version", Types.DOUBLE},
		{"acceptedDate", Types.TIMESTAMP}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("entryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("screenName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("version", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("acceptedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CuscalToC_TermsOfUse (entryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,screenName VARCHAR(75) null,version DOUBLE,acceptedDate DATE null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table CuscalToC_TermsOfUse";

	public static final String ORDER_BY_JPQL =
		" ORDER BY termsOfUse.acceptedDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CuscalToC_TermsOfUse.acceptedDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACCEPTEDDATE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TermsOfUseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _entryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TermsOfUse.class;
	}

	@Override
	public String getModelClassName() {
		return TermsOfUse.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TermsOfUse, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TermsOfUse, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TermsOfUse, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TermsOfUse)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TermsOfUse, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TermsOfUse, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TermsOfUse)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TermsOfUse, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TermsOfUse, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<TermsOfUse, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<TermsOfUse, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<TermsOfUse, Object>>();

			attributeGetterFunctions.put("entryId", TermsOfUse::getEntryId);
			attributeGetterFunctions.put("groupId", TermsOfUse::getGroupId);
			attributeGetterFunctions.put("companyId", TermsOfUse::getCompanyId);
			attributeGetterFunctions.put("userId", TermsOfUse::getUserId);
			attributeGetterFunctions.put(
				"screenName", TermsOfUse::getScreenName);
			attributeGetterFunctions.put("version", TermsOfUse::getVersion);
			attributeGetterFunctions.put(
				"acceptedDate", TermsOfUse::getAcceptedDate);
			attributeGetterFunctions.put(
				"createDate", TermsOfUse::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", TermsOfUse::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<TermsOfUse, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<TermsOfUse, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<TermsOfUse, ?>>();

			attributeSetterBiConsumers.put(
				"entryId",
				(BiConsumer<TermsOfUse, Long>)TermsOfUse::setEntryId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<TermsOfUse, Long>)TermsOfUse::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<TermsOfUse, Long>)TermsOfUse::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<TermsOfUse, Long>)TermsOfUse::setUserId);
			attributeSetterBiConsumers.put(
				"screenName",
				(BiConsumer<TermsOfUse, String>)TermsOfUse::setScreenName);
			attributeSetterBiConsumers.put(
				"version",
				(BiConsumer<TermsOfUse, Double>)TermsOfUse::setVersion);
			attributeSetterBiConsumers.put(
				"acceptedDate",
				(BiConsumer<TermsOfUse, Date>)TermsOfUse::setAcceptedDate);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<TermsOfUse, Date>)TermsOfUse::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<TermsOfUse, Date>)TermsOfUse::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getEntryId() {
		return _entryId;
	}

	@Override
	public void setEntryId(long entryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entryId = entryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getScreenName() {
		if (_screenName == null) {
			return "";
		}
		else {
			return _screenName;
		}
	}

	@Override
	public void setScreenName(String screenName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_screenName = screenName;
	}

	@JSON
	@Override
	public double getVersion() {
		return _version;
	}

	@Override
	public void setVersion(double version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@JSON
	@Override
	public Date getAcceptedDate() {
		return _acceptedDate;
	}

	@Override
	public void setAcceptedDate(Date acceptedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_acceptedDate = acceptedDate;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TermsOfUse.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TermsOfUse toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TermsOfUse>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TermsOfUseImpl termsOfUseImpl = new TermsOfUseImpl();

		termsOfUseImpl.setEntryId(getEntryId());
		termsOfUseImpl.setGroupId(getGroupId());
		termsOfUseImpl.setCompanyId(getCompanyId());
		termsOfUseImpl.setUserId(getUserId());
		termsOfUseImpl.setScreenName(getScreenName());
		termsOfUseImpl.setVersion(getVersion());
		termsOfUseImpl.setAcceptedDate(getAcceptedDate());
		termsOfUseImpl.setCreateDate(getCreateDate());
		termsOfUseImpl.setModifiedDate(getModifiedDate());

		termsOfUseImpl.resetOriginalValues();

		return termsOfUseImpl;
	}

	@Override
	public TermsOfUse cloneWithOriginalValues() {
		TermsOfUseImpl termsOfUseImpl = new TermsOfUseImpl();

		termsOfUseImpl.setEntryId(this.<Long>getColumnOriginalValue("entryId"));
		termsOfUseImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		termsOfUseImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		termsOfUseImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		termsOfUseImpl.setScreenName(
			this.<String>getColumnOriginalValue("screenName"));
		termsOfUseImpl.setVersion(
			this.<Double>getColumnOriginalValue("version"));
		termsOfUseImpl.setAcceptedDate(
			this.<Date>getColumnOriginalValue("acceptedDate"));
		termsOfUseImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		termsOfUseImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return termsOfUseImpl;
	}

	@Override
	public int compareTo(TermsOfUse termsOfUse) {
		int value = 0;

		value = DateUtil.compareTo(
			getAcceptedDate(), termsOfUse.getAcceptedDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TermsOfUse)) {
			return false;
		}

		TermsOfUse termsOfUse = (TermsOfUse)object;

		long primaryKey = termsOfUse.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TermsOfUse> toCacheModel() {
		TermsOfUseCacheModel termsOfUseCacheModel = new TermsOfUseCacheModel();

		termsOfUseCacheModel.entryId = getEntryId();

		termsOfUseCacheModel.groupId = getGroupId();

		termsOfUseCacheModel.companyId = getCompanyId();

		termsOfUseCacheModel.userId = getUserId();

		termsOfUseCacheModel.screenName = getScreenName();

		String screenName = termsOfUseCacheModel.screenName;

		if ((screenName != null) && (screenName.length() == 0)) {
			termsOfUseCacheModel.screenName = null;
		}

		termsOfUseCacheModel.version = getVersion();

		Date acceptedDate = getAcceptedDate();

		if (acceptedDate != null) {
			termsOfUseCacheModel.acceptedDate = acceptedDate.getTime();
		}
		else {
			termsOfUseCacheModel.acceptedDate = Long.MIN_VALUE;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			termsOfUseCacheModel.createDate = createDate.getTime();
		}
		else {
			termsOfUseCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			termsOfUseCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			termsOfUseCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return termsOfUseCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TermsOfUse, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TermsOfUse, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TermsOfUse, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TermsOfUse)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TermsOfUse>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TermsOfUse.class, ModelWrapper.class);

	}

	private long _entryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _screenName;
	private double _version;
	private Date _acceptedDate;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<TermsOfUse, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TermsOfUse)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("entryId", _entryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("screenName", _screenName);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("acceptedDate", _acceptedDate);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("entryId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("screenName", 16L);

		columnBitmasks.put("version", 32L);

		columnBitmasks.put("acceptedDate", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TermsOfUse _escapedModel;

}