#!/bin/sh

set -exv

export PATH=$PATH:$M2_HOME/bin

if ! ( keytool -list -keystore $JAVA_HOME/jre/lib/security/cacerts -alias cardserviced -storepass "changeit" -noprompt >/dev/null 2>&1 ) ; then
  keytool -import -alias cardserviced -trustcacerts -file repository/src/main/resources/cuscal-d.cer -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass "changeit" -noprompt
fi

cd repository/

mvn -Dmaven.wagon.http.ssl.insecure=true -X -s ./settings.xml -U test

keytool -delete -alias cardserviced -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass "changeit" -noprompt