/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package au.com.cuscal.termsofuse.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TermsOfUse service. Represents a row in the &quot;CuscalToC_TermsOfUse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>au.com.cuscal.termsofuse.model.impl.TermsOfUseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>au.com.cuscal.termsofuse.model.impl.TermsOfUseImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TermsOfUse
 * @generated
 */
@ProviderType
public interface TermsOfUseModel extends BaseModel<TermsOfUse>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a terms of use model instance should use the {@link TermsOfUse} interface instead.
	 */

	/**
	 * Returns the primary key of this terms of use.
	 *
	 * @return the primary key of this terms of use
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this terms of use.
	 *
	 * @param primaryKey the primary key of this terms of use
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this terms of use.
	 *
	 * @return the entry ID of this terms of use
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this terms of use.
	 *
	 * @param entryId the entry ID of this terms of use
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the group ID of this terms of use.
	 *
	 * @return the group ID of this terms of use
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this terms of use.
	 *
	 * @param groupId the group ID of this terms of use
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this terms of use.
	 *
	 * @return the company ID of this terms of use
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this terms of use.
	 *
	 * @param companyId the company ID of this terms of use
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this terms of use.
	 *
	 * @return the user ID of this terms of use
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this terms of use.
	 *
	 * @param userId the user ID of this terms of use
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this terms of use.
	 *
	 * @return the user uuid of this terms of use
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this terms of use.
	 *
	 * @param userUuid the user uuid of this terms of use
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the screen name of this terms of use.
	 *
	 * @return the screen name of this terms of use
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this terms of use.
	 *
	 * @param screenName the screen name of this terms of use
	 */
	public void setScreenName(String screenName);

	/**
	 * Returns the version of this terms of use.
	 *
	 * @return the version of this terms of use
	 */
	public double getVersion();

	/**
	 * Sets the version of this terms of use.
	 *
	 * @param version the version of this terms of use
	 */
	public void setVersion(double version);

	/**
	 * Returns the accepted date of this terms of use.
	 *
	 * @return the accepted date of this terms of use
	 */
	public Date getAcceptedDate();

	/**
	 * Sets the accepted date of this terms of use.
	 *
	 * @param acceptedDate the accepted date of this terms of use
	 */
	public void setAcceptedDate(Date acceptedDate);

	/**
	 * Returns the create date of this terms of use.
	 *
	 * @return the create date of this terms of use
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this terms of use.
	 *
	 * @param createDate the create date of this terms of use
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this terms of use.
	 *
	 * @return the modified date of this terms of use
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this terms of use.
	 *
	 * @param modifiedDate the modified date of this terms of use
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public TermsOfUse cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}