INSERT INTO "SELF_SERVICE"."TKT_CATEGORY" (ID, TKT_DEST_ID, DEST_ID, NAME, DESCRIPTION, DISPLAY_ORDER, IS_ACTIVE) VALUES ('3', '0', '0', 'DE Trace', 'DE Trace', '0', 'Y')
INSERT INTO "SELF_SERVICE"."TKT_CATEGORY" (ID, TKT_DEST_ID, DEST_ID, NAME, DESCRIPTION, DISPLAY_ORDER, IS_ACTIVE) VALUES ('4', '0', '0', 'DE Recall', 'DE Recall', '0', 'Y')
INSERT INTO "SELF_SERVICE"."TKT_CATEGORY" (ID, TKT_DEST_ID, DEST_ID, NAME, DESCRIPTION, DISPLAY_ORDER, IS_ACTIVE) VALUES ('5', '0', '0', 'DE Mistaken Internet Payment', 'DE Mistaken Internet Payment', '0', 'Y')
INSERT INTO "SELF_SERVICE"."TKT_CATEGORY" (ID, TKT_DEST_ID, DEST_ID, NAME, DESCRIPTION, DISPLAY_ORDER, IS_ACTIVE) VALUES ('6', '0', '0', 'DE Claim', 'DE Claim', '0', 'Y')



INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (300,'DE.FI_INSTITUTION_NAME');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (301,'DE.FI_INSTITUTION_USER_ID');
//INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (302,'DE.PROCESSED_DATE');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (303,'DE.DESTINATION_BSB');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (304,'DE.DESTINATION_ACCOUNT_NUMBER');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (305,'DE.TRANSACTION_CODE');
//INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (306,'DE.TRANSACTION_AMOUNT');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (307,'DE.ACCOUNT_TITLE');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (308,'DE.FI_INSTITUTION_TRACE_BSB');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (309,'DE.REMITTER_ACCOUNT_NUM');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (310,'DE.REMITTER_NAME');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (311,'DE.DESTINATION_ADDITIONAL_INFO');
//INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (312,'DE.DESTINATION_LODGEMENT_REF');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (313,'DE.DATE_POSTED');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (314,'DE.RECEIVER_BSB');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (315,'DE.RECEIVER_BRANCH');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (316,'DE.RECEIVER_ACCOUNT_NUMBER');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (317,'DE.RECEIVER_ACCOUNT_NAME');

//Mistaken Payment specific
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (318,'DE.RECEIVER_LODGEMENT_REF');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (319,'DE.INTENDED_ACCOUNT_BSB_NUMBER');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (320,'DE.INTENDED_ACCOUNT_NUMBER');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (321,'DE.INTENDED_ACCOUNT_TITLE');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (322,'DE.CUSTOMER_DECLARATION_ATTACHED');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (323,'DE.REQUEST_RECEIVED');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (324,'DE.FUNDS_AVAILABLE');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (325,'DE.OUTCOME');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (326,'DE.RECEIVER_ADDITIONAL_INFO');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (327,'DE.LEDGER_ADDITIONAL_INFO');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (328,'DE.TIME_FRAME');

//Claims
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (329,'DE.CLAIM_REPLY');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (330,'DE.CLAIM_ADDITIONAL_INFO');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (331,'DE.CLAIM_REASON');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (332,'DE.BATCH_NUMBER');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (333,'DE.CURRENT_DDR_STATUS');

//for add-0n requirement from Ben
//common for all three forms DE Trace, Recall, Mistaken Payment
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (334,'DE.CLIENT_REF_NUMBER');
//DE Recall
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (335,'DE.REFERENCE');
//DE Trace
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (336,'DE.REQUEST_FOR');
//DE Mistaken Payment
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (337,'DE.INTENDED_ACCOUNT_DETAILS');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (338,'DE.CUSTOMER_SELECTED_WRONG_PAYEE');

//DE Claims- multi claims requirement
//Date debited
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (339,'DE.PROCESSED_DATE1');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (340,'DE.PROCESSED_DATE2');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (341,'DE.PROCESSED_DATE3');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (342,'DE.PROCESSED_DATE4');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (343,'DE.PROCESSED_DATE5');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (344,'DE.PROCESSED_DATE6');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (345,'DE.PROCESSED_DATE7');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (346,'DE.PROCESSED_DATE8');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (347,'DE.PROCESSED_DATE9');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (348,'DE.PROCESSED_DATE10');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (349,'DE.PROCESSED_DATE11');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (350,'DE.PROCESSED_DATE12');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (351,'DE.PROCESSED_DATE13');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (352,'DE.PROCESSED_DATE14');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (353,'DE.PROCESSED_DATE15');
//INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (354,'DE.PROCESSED_DATE16');

//Lodgement Reference
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (355,'DE.DESTINATION_LODGEMENT_REF1');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (356,'DE.DESTINATION_LODGEMENT_REF2');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (357,'DE.DESTINATION_LODGEMENT_REF3');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (358,'DE.DESTINATION_LODGEMENT_REF4');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (359,'DE.DESTINATION_LODGEMENT_REF5');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (360,'DE.DESTINATION_LODGEMENT_REF6');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (361,'DE.DESTINATION_LODGEMENT_REF7');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (362,'DE.DESTINATION_LODGEMENT_REF8');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (363,'DE.DESTINATION_LODGEMENT_REF9');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (364,'DE.DESTINATION_LODGEMENT_REF10');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (365,'DE.DESTINATION_LODGEMENT_REF11');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (366,'DE.DESTINATION_LODGEMENT_REF12');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (367,'DE.DESTINATION_LODGEMENT_REF13');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (368,'DE.DESTINATION_LODGEMENT_REF14');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (369,'DE.DESTINATION_LODGEMENT_REF15');

//Amount
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (370,'DE.TRANSACTION_AMOUNT1');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (371,'DE.TRANSACTION_AMOUNT2');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (372,'DE.TRANSACTION_AMOUNT3');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (373,'DE.TRANSACTION_AMOUNT4');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (374,'DE.TRANSACTION_AMOUNT5');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (375,'DE.TRANSACTION_AMOUNT6');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (376,'DE.TRANSACTION_AMOUNT7');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (377,'DE.TRANSACTION_AMOUNT8');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (378,'DE.TRANSACTION_AMOUNT9');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (379,'DE.TRANSACTION_AMOUNT10');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (380,'DE.TRANSACTION_AMOUNT11');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (381,'DE.TRANSACTION_AMOUNT12');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (382,'DE.TRANSACTION_AMOUNT13');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (383,'DE.TRANSACTION_AMOUNT14');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (384,'DE.TRANSACTION_AMOUNT15');


commit;



INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (215,'BPAY.SB_CLIENT_ITEM_NUMBER');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (214,'BPAY.INVESTIGATION_ID');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (213,'BPAY.MEMBER_NAME');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (212,'BPAY.BILLER_NAME');

INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (211,'BPAY.COMMENT');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (210,'BPAY.REASON');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (209,'BPAY.PAYER_NAME');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (208,'BPAY.MEMBER_NUMBER');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (207,'BPAY.CORRECT_CRN');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (206,'BPAY.ENTRY_METHOD');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (205,'BPAY.PAYMENT_METHOD');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (204,'BPAY.PAYMENT_AMOUNT');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (203,'BPAY.CRN');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (202,'BPAY.BILLER_CODE');

INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (201,'BPAY.TRANSACTION_DATE');
INSERT INTO SELF_SERVICE.TKT_ATTRIBUTES_TYPE ("ID","TYPE") VALUES (200,'BPAY.TRANSACTION_REF_NUMBER');


INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, CREATION_TIMESTAMP, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('700', '200', 'BPay', 'Bpay Transaction reference number')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('701', '201', 'BPay', 'Bpay Transaction date')

INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('702', '202', 'BPay', 'Bpay Biller code');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('703', '203', 'BPay', 'Bpay Customer Reference Number');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('704', '204', 'BPay', 'Bpay Payment amount');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('705', '205', 'BPay', 'Bpay Payment method');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('706', '206', 'BPay', 'Bpay Entry method');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('707', '207', 'BPay', 'Bpay Correct CRN');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('708', '208', 'BPay', 'Bpay Member number');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('709', '209', 'BPay', 'Bpay Payer''s name');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('710', '210', 'BPay', 'Bpay reason for request');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('711', '211', 'BPay', 'Bpay Comment');


INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('712', '212', 'BPay', 'Bpay Biller name');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('713', '213', 'BPay', 'Bpay Member name');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('714', '214', 'BPay', 'Bpay Investigation id');
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID, ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('715', '215', 'BPay', 'Bpay SB Client Item number');



INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('800', '300', 'DE', 'Name of the FI who sent the transaction')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('801', '301', 'DE', 'User ID of the FI who sent the transaction')
//INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('802', '302', 'DE', 'Date the DE file being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('803', '303', 'DE', 'BSB number of where was the transaction was being sent to')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('804', '304', 'DE', 'Account Number to be Credited')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('805', '305', 'DE', 'Transaction Code')
//INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('806', '306', 'DE', 'Transaction amount being traced')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('807', '307', 'DE', 'Name of account funds were sent to')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('808', '308', 'DE', 'FI trace BSB number')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('809', '309', 'DE', 'Account number the funds originally came from')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('810', '310', 'DE', 'Name of remitter')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('811', '311', 'DE', 'Additional information w.r.t destination')
//INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('812', '312', 'DE', 'Lodgement reference')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('813', '313', 'DE', 'Date posted')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('814', '314', 'DE', 'BSB number the funds are being sent to')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('815', '315', 'DE', 'Receiver branch')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('816', '316', 'DE', 'Account details of the person or institution who should receive the funds if the recall is successful')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('817', '317', 'DE', 'Name of the person who should receive the funds')


//Mistaken Payment specific
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('818', '318', 'DE', 'Lodgement reference w.r.t. receiver')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('819', '319', 'DE', 'Intended account BSB number')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('820', '320', 'DE', 'Intended account number')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('821', '321', 'DE', 'Intended account title')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('822', '322', 'DE', 'Customer declaration attached')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('823', '323', 'DE', 'Request received')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('824', '324', 'DE', 'Funds available')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('825', '325', 'DE', 'Outcome')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('826', '326', 'DE', 'Receiver additional information')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('827', '327', 'DE', 'Ledger additional information')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('828', '328', 'DE', 'Time frame')

//Claims
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('829', '329', 'DE', 'Claim reply')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('830', '330', 'DE', 'Additional infomation to support claim')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('831', '331', 'DE', 'Reason for claim')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('832', '332', 'DE', 'Batch number for original debit')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('833', '333', 'DE', 'A current DDR was held at the time drawing was received')

//for add-0n requirement from Ben
//common for all three forms DE Trace, Recall, Mistaken Payment
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('834', '334', 'DE', 'Client reference number')
//DE Recall
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('835', '335', 'DE', 'Reference')
//DE Trace
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('836', '336', 'DE', 'Request for')
//DE Mistaken Payment
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('837', '337', 'DE', 'Intended Account Details')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('838', '338', 'DE', 'Customer selected wrong payee')

//DE Claims- multi claims requirement
//Date debited
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('839', '339', 'DE', 'Date the DE file for transaction1 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('840', '340', 'DE', 'Date the DE file for transaction2 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('841', '341', 'DE', 'Date the DE file for transaction3 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('842', '342', 'DE', 'Date the DE file for transaction4 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('843', '343', 'DE', 'Date the DE file for transaction5 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('844', '344', 'DE', 'Date the DE file for transaction6 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('845', '345', 'DE', 'Date the DE file for transaction7 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('846', '346', 'DE', 'Date the DE file for transaction8 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('847', '347', 'DE', 'Date the DE file for transaction9 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('848', '348', 'DE', 'Date the DE file for transaction10 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('849', '349', 'DE', 'Date the DE file for transaction11 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('850', '350', 'DE', 'Date the DE file for transaction12 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('851', '351', 'DE', 'Date the DE file for transaction13 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('852', '352', 'DE', 'Date the DE file for transaction14 being traced was processed')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('853', '353', 'DE', 'Date the DE file for transaction15 being traced was processed')
//INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('854', '354', 'DE', 'Date the DE file for transaction16 being traced was processed')

//Lodgement Reference
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('855', '355', 'DE', 'Lodgement reference for transaction1')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('856', '356', 'DE', 'Lodgement reference for transaction2')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('857', '357', 'DE', 'Lodgement reference for transaction3')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('858', '358', 'DE', 'Lodgement reference for transaction4')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('859', '359', 'DE', 'Lodgement reference for transaction5')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('860', '360', 'DE', 'Lodgement reference for transaction6')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('861', '361', 'DE', 'Lodgement reference for transaction7')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('862', '362', 'DE', 'Lodgement reference for transaction8')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('863', '363', 'DE', 'Lodgement reference for transaction9')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('864', '364', 'DE', 'Lodgement reference for transaction10')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('865', '365', 'DE', 'Lodgement reference for transaction11')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('866', '366', 'DE', 'Lodgement reference for transaction12')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('867', '367', 'DE', 'Lodgement reference for transaction13')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('868', '368', 'DE', 'Lodgement reference for transaction14')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('869', '369', 'DE', 'Lodgement reference for transaction15')

//Amount
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('870', '370', 'DE', 'Transaction amount being traced for transaction1')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('871', '371', 'DE', 'Transaction amount being traced for transaction2')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('872', '372', 'DE', 'Transaction amount being traced for transaction3')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('873', '373', 'DE', 'Transaction amount being traced for transaction4')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('874', '374', 'DE', 'Transaction amount being traced for transaction5')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('875', '375', 'DE', 'Transaction amount being traced for transaction6')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('876', '376', 'DE', 'Transaction amount being traced for transaction7')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('877', '377', 'DE', 'Transaction amount being traced for transaction8')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('878', '378', 'DE', 'Transaction amount being traced for transaction9')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('879', '379', 'DE', 'Transaction amount being traced for transaction10')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('880', '380', 'DE', 'Transaction amount being traced for transaction11')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('881', '381', 'DE', 'Transaction amount being traced for transaction12')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('882', '382', 'DE', 'Transaction amount being traced for transaction13')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('883', '383', 'DE', 'Transaction amount being traced for transaction14')
INSERT INTO "SELF_SERVICE"."TKT_ATTRIBUTES_LIST" (ID,  ATTRIBUTES_TYPE_ID, VALUE, DESCRIPTION) VALUES ('884', '384', 'DE', 'Transaction amount being traced for transaction15')





INSERT INTO "SELF_SERVICE"."TKT_USER" (ID, CREATION_TIMESTAMP, CREATED_BY, LAST_UPDATED_TIMESTAMP, LAST_UPDATED_BY, ORG_SHORT_NAME, USER_ID, FNAME, SNAME, FULLNAME, PHONE, EMAIL) VALUES ('11901', TO_TIMESTAMP('14/MAY/14', 'DD/MON/RR HH12:MI:SS.FF AM'), '11901', TO_TIMESTAMP('14/MAY/14', 'DD/MON/RR HH12:MI:SS.FF AM'), '51111', 'cuscal', 'rkumar', 'Rajeev', 'Kumar', 'rajeevkumar', '02)829999166', 'rkumar@cuscal.com.au');
