//
// Decompiled by Procyon v0.6-prerelease

//

package au.com.cuscal.chargeback.common;

public enum AttributesTypeType {

	DISPUTE_AMOUNT("DISPUTE.AMOUNT"), DOCUMENT_INDICATOR("DOCUMENT.INDICATOR"),
	MESSAGE_TYPE("MESSAGE.TYPE"), FUNCTION_CODE("FUNCTION.CODE"),
	MASTERCARD_DISPUTE_TYPE("MASTERCARD.DISPUTE.TYPE"),
	MASTERCARD_RETRIEVAL_REQUEST("MASTERCARD.RETRIEVAL.REQUEST"),
	MASTERCARD_FIRST_CHARGEBACK("MASTERCARD.FIRST.CHARGEBACK"),
	MASTERCARD_ARBITRATION_CHARGEBACK("MASTERCARD.ARBITRATION.CHARGEBACK"),
	POS_CONDITION_CODE("POS.CONDITION.CODE"),
	POS_CONDITION_DESCRIPTION("POS.CONDITION.DESCRIPTION"),
	POS_ENTRY_MODE_CODE("POS.ENTRY.MODE.CODE"),
	POS_ENTRY_MODE_DESCRIPTION("POS.ENTRY.MODE.DESCRIPTION"),
	UCAF_COLLECTION_INDICATOR("UCAF.COLLECTION.INDICATOR"),
	ELECTRONIC_COMMERCE_INDCIATOR("ELECTRONIC.COMMERCE.INDCIATOR"),
	CENTRAL_SITE_BUSINESS_DATE("CENTRAL.SITE.BUSINESS.DATE"),
	CHIP_CARD_PRESENT("CHIP.CARD.PRESENT"),
	TRACK_2_DATA_SERVICE_CODE("TRACK.2.DATA.SERVICE.CODE");

	public String getValue() {
		return this.value;
	}

	private AttributesTypeType(final String value) {
		this.value = value;
	}

	private String value;

}