name: Java CI with Gradle
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      - name: Build with Gradle Wrapper
        run: ./gradlew build
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21.0.8
          distribution: adopt
      - name: Make gradlew executable
        run: |
          chmod +x ./gradlew
      - name: Add fragments to deploy folder
        run: |
          mkdir -p configs/common/deploy
          cd fragments/
          for file in *; do zip -r ${file%.*}.zip $file/; done
          cp *.zip ../configs/common/deploy/
          rm *.zip
      - name: Build Liferay Bundle
    env:
      GH_MAVEN_PACKAGES_READ_USER_NAME: '${{ secrets.GH_MAVEN_PACKAGES_READ_USER_NAME }}'
      GH_MAVEN_PACKAGES_READ_PASSWORD: '${{ secrets.GH_MAVEN_PACKAGES_READ_PASSWORD }}'
    run: |
      #!/bin/sh
      npm -v
      node -v
      npm config set strict-ssl false
      export GRADLE_OPTS="-Xms1724m -Xmx5048m"
      java -version
      ./gradlew clean
      ./gradlew "-Pliferay.workspace.environment=common" distBundleZip 
