name: Java 21 Manual Build with Gradle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin 21.0.8)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0.8'

      # Step 2: Install Liferay Blade CLI (Official Liferay Method)
      - name: 🚀 Install Liferay Blade CLI (official installer)
        run: |
          echo "🚀 Installing Liferay Blade CLI (official installer)..."
          curl -L https://raw.githubusercontent.com/liferay/liferay-blade-cli/master/cli/installers/local | sh
          echo "✅ Blade CLI Installed Successfully"
          # Add Blade to PATH for current session
          # echo "/home/runner/jpm/bin" >> $GITHUB_PATH
          # Verify installation
          blade version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean
