name: Java 21 Manual Build with Gradle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin 21.0.8)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0.8'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Add fragments to deploy folder
        run: |
          mkdir -p configs/common/deploy
          cd fragments/
          for file in *; do zip -r ${file%.*}.zip $file/; done
          cp *.zip ../configs/common/deploy/
          rm *.zip

      - name: 🚀 Install Liferay Blade CLI (official installer)
        run: |
          echo "🚀 Installing Liferay Blade CLI..."
          curl -L https://raw.githubusercontent.com/liferay/liferay-blade-cli/master/cli/installers/local | sh
        # Add Blade CLI to PATH for the rest of the workflow
      - name: Add Blade CLI to PATH
        run: echo "/home/runner/jpm/bin" >> $GITHUB_PATH

      - name: Verify Blade CLI installation
        run: blade version

      - name: Build with Gradle
        run: |
          npm -v
          node -v
          npm config set strict-ssl false
          export GRADLE_OPTS="-Xms1724m -Xmx5048m"
          java -version
          ./gradlew -version
          blade gw clean deploy
